Added Pagination
web3phl/directory pull request #64
Opened 2022-10-04 04:22 UTC by rgvillanueva28

PR for #41

2022-10-04 06:13 UTC, jnebab commented on src/components/Pagination.tsx
> +  console.log(length / size);
please remove this console log

2022-10-04 06:24 UTC, jnebab commented on src/components/Pagination.tsx
> +          disabled={length / size <= page}
you can use the `directories.hasNextPage` bool to replace this condition.

2022-10-04 06:35 UTC, jnebab commented on src/components/Pagination.tsx
> +        <strong>{length >= size * page ? size * page : length}</strong> of{" "}
You can also use `hasNextPage` here.

2022-10-04 06:42 UTC, jnebab commented
Hi @rgvillanueva28, we thank you for your contribution. Kindly check the feedback. Thank you.

2022-10-04 10:21 UTC, jnebab commented
lgtm

2022-10-05 15:51 UTC, jnebab requested changes

2022-10-05 15:51 UTC, jnebab commented on src/components/Pagination.tsx
> +          className=" flex flex-row items-center space-x-3 rounded-r-md border-l border-white bg-gray-700 py-2 px-4 text-white hover:bg-gray-600 disabled:cursor-not-allowed disabled:bg-gray-500"
```suggestion
          className=" flex flex-row items-center space-x-3 rounded-r-md border-l border-white bg-gradient-to-r from-purple-900 to-violet-500 py-2 px-4 text-white hover:bg-gray-600 disabled:cursor-not-allowed disabled:bg-gray-500"
```

2022-10-10 18:32 UTC, warengonzaga approved these changes
LGTM ✌️

2022-10-10 18:33 UTC, warengonzaga commented
Found an issue @rgvillanueva28 not sure why it shows like this?
![image](https://user-images.githubusercontent.com/15052701/194931375-69f972b8-c339-4a8f-b0ce-5fc67f17a2e9.png)

cc: @jnebab @kquirapas

2022-10-10 18:37 UTC, warengonzaga commented
> Any error messages? @warengonzaga

I don't see any error messages but with every turn of pages, it has 2 missing items.

2022-10-10 18:39 UTC, jnebab commented
> Found an issue @rgvillanueva28 not sure why it shows like this? ![image](https://user-images.githubusercontent.com/15052701/194931375-69f972b8-c339-4a8f-b0ce-5fc67f17a2e9.png)
> 
> cc: @jnebab @kquirapas

This actually make sense. Since the pagination is only getting 10 items at a time and the grid is in 3 columns. so for 10 items, it will have 3 columns and 4 rows with the 4th row with one item only. Maybe we can make it 12 items per page to fill  it up correctly

2022-10-10 18:39 UTC, warengonzaga commented
> > Found an issue @rgvillanueva28 not sure why it shows like this? ![image](https://user-images.githubusercontent.com/15052701/194931375-69f972b8-c339-4a8f-b0ce-5fc67f17a2e9.png)
> > cc: @jnebab @kquirapas
> 
> This actually make sense. Since the pagination is only getting 10 items at a time and the grid is in 3 columns. so for 10 items, it will have 3 columns and 4 rows with the 4th row with one item only. Maybe we can make it 12 items per page to fill it up correctly

Yeah let's make it 12 to fill up the missing 2 items.

2022-10-10 18:42 UTC, jnebab commented
@rgvillanueva28, please update it to 12 per page. Thanks for the help :)

2022-10-11 14:39 UTC, jnebab approved these changes
lgtm.

2022-10-11 19:14 UTC, warengonzaga approved these changes
LGTM

2022-10-11 19:16 UTC, merged